- name: Stop Eth2 validator client container
  shell: "docker stop --time=10 {{validator_container_name}}"
  when: has_validator_client
  register: stop_result
  failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"

- name: Stop Eth2 beacon node if no separate validator client
  shell: "docker stop --time=10 {{beacon_container_name}}"
  when: not has_validator_client
  register: stop_result
  failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"

- name: Where wallet
  debug:
    msg: "remote output data in '{{remote_out_data_dir}}'"
  delegate_to: localhost
- name: Remove old local output data
  file:
    path: "{{remote_out_data_dir}}"
    state: absent
  delegate_to: localhost
- name: Remove old output archive
  file:
    path: "{{remote_out_data_archive}}"
    state: absent
  delegate_to: localhost
- name: Ensure local data dir exists
  file:
    path: "{{validator_local_data_dir}}"
    state: directory
  delegate_to: localhost
- name: Prepare validator keys
  delegate_to: localhost
  shell: >
    eth2-val-tools keystores
    --key-man-loc="{{validator_container_dir}}/wallets"
    --out-loc="{{remote_out_data_dir}}"
    --source-max="{{validators_source_max}}"
    --source-min="{{validators_source_min}}"
    --source-mnemonic="{{validators_source_mnemonic}}"

- name: Create remote out selected directory
  file:
    path: "{{ remote_out_data_dir }}/selected"
    state: directory
  delegate_to: localhost
- name: Select files for client
  vars:
    input_data_dir: "{{remote_out_data_dir}}"
    output_data_dir: "{{remote_out_data_dir}}/selected"
  include_tasks: "pick-keys-{{eth2client_name}}.yml"
- name: Archive selected data before upload
  archive:
    path: "{{remote_out_data_dir}}/selected/*"
    dest: "{{remote_out_data_archive}}"
  delegate_to: localhost
- name: Prepare dest directory in BN
  file:
    path: "{{ beacon_host_dir }}/"
    state: directory
  when: (not has_validator_client) and (validators_source_min < validators_source_max)
- name: Prepare dest directory in VC
  file:
    path: "{{ validator_host_dir }}/"
    state: directory
    mode: '0750'
  when: has_validator_client and (validators_source_min < validators_source_max)
- name: Upload new validator accounts to BN
  unarchive:
    src: "{{ remote_out_data_archive }}"
    dest: "{{ beacon_host_dir }}/"
    mode: "0700"  # execute bit, to iterate directory
    owner: "1000"
    group: "1000"
  become: true
  when: (not has_validator_client) and (validators_source_min < validators_source_max)
- name: Upload new validator accounts to VC
  unarchive:
    src: "{{ remote_out_data_archive }}"
    dest: "{{ validator_host_dir }}/"
    mode: "0700"  # execute bit, to iterate directory
    owner: "1000"
    group: "1000"
  become: true
  when: has_validator_client and (validators_source_min < validators_source_max)
- block:
    - name: Pull and restart validator client
      vars:
        validator_require_restart: true
      include_tasks: "start-validator.yml"
      when: has_validator_client and (validators_source_min < validators_source_max)
    - name: Or restart beacon node, if no separate beacon node
      vars:
        beacon_require_restart: true
      include_tasks: "start-beacon.yml"
      when: (not has_validator_client) and (validators_source_min < validators_source_max)
  when: restart_validator_afterwards | default(false)
