- name: Stop Eth2 validator client container
  shell: "docker stop --time=10 {{validator_container_name}}"
  when: has_validator_client
  register: stop_result
  failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"

- name: Stop Eth2 beacon node if no separate validator client
  shell: "docker stop --time=10 {{beacon_container_name}}"
  when: not has_validator_client
  register: stop_result
  failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"

- name: Wipe validator current keys
  include_tasks: "wipe-validator-keys-{{eth2client_name}}.yml"

- name: Where wallet
  debug:
    msg: "prep data in '{{validator_local_prep_host_dir}}', remote select data in '{{validator_local_select_host_dir}}', out data in '{{validator_local_output_host_archive}}'"
  delegate_to: localhost
- name: Remove old local selected data
  file:
    path: "{{validator_local_select_host_dir}}"
    state: absent
  delegate_to: localhost
- name: Remove old output archive
  file:
    path: "{{validator_local_output_host_archive}}"
    state: absent
  delegate_to: localhost
- name: Ensure local output parent dir exists
  file:
    path: "{{validator_local_output_dir}}"
    state: directory
  delegate_to: localhost
- name: Create remote out selected directory
  file:
    path: "{{ validator_local_select_host_dir }}"
    state: directory
  delegate_to: localhost
- name: Select files for client
  vars:
    input_data_dir: "{{validator_local_prep_host_dir}}"
    output_data_dir: "{{validator_local_select_host_dir}}"
  include_tasks: "pick-keys-{{eth2client_name}}.yml"
- name: Archive selected data before upload
  archive:
    path: "{{validator_local_select_host_dir}}/*"
    dest: "{{validator_local_output_host_archive}}"
  delegate_to: localhost
- name: Prepare dest directory in BN
  file:
    path: "{{ beacon_host_dir }}/"
    state: directory
  when: not has_validator_client
- name: Prepare dest directory in VC
  file:
    path: "{{ validator_host_dir }}/"
    state: directory
    mode: '0750'
  when: has_validator_client
- name: Upload new validator accounts to BN
  unarchive:
    src: "{{ validator_local_output_host_archive }}"
    dest: "{{ beacon_host_dir }}/"
    mode: "{{beacon_keystores_file_mode}}"
#    owner: "1000"
#    group: "1000"
  become: true
  when: not has_validator_client
- name: Upload new validator accounts to VC
  unarchive:
    src: "{{ validator_local_output_host_archive }}"
    dest: "{{ validator_host_dir }}/"
    mode: "{{beacon_keystores_file_mode}}"
#    owner: "1000"
#    group: "1000"
  become: true
  when: has_validator_client
# No automatic restart! Be careful with deploying validators!
