- name: 'Ensure metric pusher is not present'
  cron:
    name: "metric-pusher"
    state: absent
    user: "{{ ansible_user }}"

- name: 'Remove the metric pusher file'
  become: true
  file:
    path: /opt/metric-pusher.sh
    state: absent