- name: Deposit contract address
  debug:
    msg: "Sending {{deposit_datas|length}} deposits to {{deposit_contract_address}} (network {{eth1_network_name}}) from {{eth1_from_addr}}"
- name: Execute deposits (unsafe, testnet use only)
  # We loop over the dynamic fact variable set by `build_deposits.yml` task
  with_items: "{{deposit_datas}}"
  shell: >
    ethereal beacon deposit
    --allow-unknown-contract="{{force_deposit}}"
    --address="{{deposit_contract_address}}"
    --network="{{eth1_network_name}}"
    --data='{{item}}'
    --value="{{deposit_actual_value}}"
    --from="{{eth1_from_addr}}"
    --privatekey="{{eth1_from_priv}}"
  loop_control:
    label: "pubkey 0x{{ (item | from_json)['pubkey'] }}"
    pause: "{{deposit_pause_seconds}}"
