keystores_container_dir: "{{validator_container_dir}}/validators"
secrets_container_dir: "{{validator_container_dir}}/secrets"

keystores_host_dir: "{{validator_host_dir}}/validators"
secrets_host_dir: "{{validator_host_dir}}/secrets"

validator_memory: 400m

# add the following back post altona
#  {% if testnet_type == 'custom' %}
#  --testnet-dir="{{validator_container_dir}}/custom_testnet_config"
validator_image_name: sigp/lighthouse:latest
validator_start_args: >
  lighthouse
  {% if testnet_type == 'medalla' %}
  --network=medalla
  {% elif testnet_type == 'zinken' %}
  --network=zinken
  {% elif testnet_type == 'toledo' %}
  --network=toledo
  {% elif testnet_type == 'pyrmont' %}
  --network=pyrmont
  {% elif testnet_type == 'mainnet' %}
  --network=mainnet
  {% elif testnet_type == 'prater' %}
  --network=prater
  {% elif eth2_network_name == 'altairDevnet0' %}
  --network=altair-devnet-0
  {% elif eth2_network_name == 'altairDevnet1' %}
  --network=altair-devnet-1
  {% elif testnet_type == 'custom' %}
  --testnet-dir="{{beacon_container_dir}}/custom_testnet_config"
  {% endif %}
  vc
  --validators-dir="{{keystores_container_dir}}"
  --secrets-dir="{{secrets_container_dir}}"
  --init-slashing-protection
  --server=http://localhost:{{beacon_rpc_port}}/
  --http --http-port={{validator_rpc_port}}


beacon_keystores_file_mode: "0700"
