keystores_container_dir: "{{validator_container_dir}}/validators"
secrets_container_dir: "{{validator_container_dir}}/secrets"

keystores_host_dir: "{{validator_host_dir}}/validators"
secrets_host_dir: "{{validator_host_dir}}/secrets"

validator_memory: 400m

validator_image_name: sigp/lighthouse:latest
validator_start_args: >
  lighthouse
  {% if testnet_type == 'custom' %}
  --testnet-dir="{{validator_container_dir}}/custom_testnet_config"
  {% elif testnet_type == 'altona' %}
  --testnet=altona
  {% elif testnet_type == 'medalla' %}
  --testnet=medalla
  {% elif testnet_type == 'zinken' %}
  --testnet=zinken
  {% elif testnet_type == 'toledo' %}
  --testnet=toledo
  {% elif testnet_type == 'pyrmont' %}
  --testnet=pyrmont
  {% endif %}
  vc
  --validators-dir="{{keystores_container_dir}}"
  --secrets-dir="{{secrets_container_dir}}"
  --init-slashing-protection
  --server=http://localhost:{{beacon_rpc_port}}/


beacon_keystores_file_mode: "0700"
