---
# defaults file for eth2-fork-mon

# general config
forkmon_dir: /home/ubuntu/forkmon
eth2-forkmon-image: ralexstokes/eth2-fork-mon:latest
forkmon_require_restart: true
forkmon_http_listen_port: 5081

forkmon_endpoints:
  - addr: http://localhost:4000
    eth1: ""


network_name: test
seconds_per_slot: 12
genesis_time: 1625745600
slots_per_epoch: 32

