- name: Docker with dependencies and user role
  become: true
  block:
    - name: Docker
      include_role:
        name: geerlingguy.docker
    - name: Docker Python wrapper
      apt:
        name: python3-docker
        state: present
    - name: Add ansible user to docker group
      shell: 'usermod -aG docker {{ ansible_user }}'
