- name: Setup general
  hosts:
    - eth2client
    - bootnode
    - metrics
    - eth2stats_server
  gather_facts: true  # Needed to check if 'ansible_distribution_release' is 'bionic'
  tasks:
    - name: "Do ubuntu universe repo setup"
      include_role:
        name: ubuntu
        tasks_from: universe
    - name: "Do docker extras setup, assume docker is installed"
      include_role:
        name: machine
        tasks_from: docker
