- name: Assign validators
  # each validator client is running on a machine with a beacon node, change this later.
  hosts: beacon_node
  gather_facts: false
  tasks:
    - name: Deploy validator keys
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: assign-validators
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic
      when: validator_enabled

- name: Start beacon nodes (and optional in-beacon validators)
  hosts: beacon_node
  gather_facts: false
  tasks:
    - name: Start beacon containers
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: start-beacon
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic

- name: Start validator clients
  hosts: beacon_node
  gather_facts: false
  tasks:
    - name: Start validator containers
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: start-validator
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic
      when: validator_enabled

- name: Start eth2stats
  hosts: beacon_node
  gather_facts: false
  tasks:
    - name: Start eth2stats containers
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: start-eth2stats
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic
      when: eth2stats_enabled

- name: Setup node collector for local metric collection
  hosts: beacon_node
  gather_facts: false
  become: true
  tasks:
    - name: Start node exporter
      include_role:
        name: external_roles/cloudalchemy.node-exporter
        tasks_from: main.yml
      when: push_metrics_enabled

- name: Start metrics push cronjob
  hosts: beacon_node
  gather_facts: false
  tasks:
    - name: Start metrics cronjob
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: start-client-metric-push
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic
      when: push_metrics_enabled