- name: Configure grafana and prometheus
  include_tasks: configure.yml
- name: Update dashboards
  include_tasks: update-dashboards.yml
- name: Start nginx reverse proxy and vhost companion
  include_tasks: start-nginx-proxy.yml
- name: Start prometheus-grafana network
  include_tasks: start-network.yml
- name: Start alertmanager
  include_tasks: start-alertmanager.yml
- name: Start prometheus
  include_tasks: start-prometheus.yml
  vars:
    prometheus_require_restart: true
- name: Setup grafana
  include_tasks: start-grafana.yml
  vars:
    grafana_require_restart: true
- name: Start prometheus pushgateway
  include_role:
    name: metrics
    tasks_from: start-prometheus-pushgateway
- name: Start cadvisor
  include_tasks: start-cadvisor.yml
  vars:
    cadvisor_require_restart: true
  when: setup_cadvisor
