- name: Run push-gateway for instances to push metrics to
  docker_container:
    name: pushgateway
    image: prom/pushgateway
    restart_policy: unless-stopped
    network_mode: bridge
    networks:
      - name: "{{grafana_prometheus_network_name}}"
        ipv4_address: "172.1.1.102"
    exposed_ports:
      - 9091
    ports:
      - "9091:9091"
    state: started

