- name: Download node exporter from Github
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract the file to tmp
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: true

- name: Stat the node exporter
  stat:
    path: /tmp/node_exporter-1.0.1.linux-amd64/node_exporter
  register: exporter_stat

- name: Move the bin to exec location
  command: mv /tmp/node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
  when: exporter_stat.stat.exists

- name: Create group
  group:
    name: node_exporter
    state: present

- name: Create user
  user:
    name: node_exporter
    state: present
    group: node_exporter
    shell: "/sbin/nologin"

- name: Create dir for collector
  file:
    path: /var/lib/node_exporter/textfile_collector
    state: directory
    recurse: yes
    owner: node_exporter
    group: node_exporter

- name: Copy the systemD unit file
  copy:
    src: files/prometheus-node-exporter/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Stop node_exporter service
  systemd:
    state: stopped
    name: node_exporter

- name: Reload systemD
  systemd:
    daemon_reload: yes

- name: Enable node exporter
  systemd:
    name: node_exporter
    enabled: yes
    masked: no

- name: Start node_exporter service
  systemd:
    state: started
    name: node_exporter
