- name: Stop node_exporter service
  systemd:
    state: stopped
    name: node_exporter
  ignore_errors: yes

- name: Disable node exporter
  systemd:
    name: node_exporter
    enabled: no
    masked: no
  ignore_errors: yes

- name: Delete the systemD unit file
  file:
    path: /etc/systemd/system/node_exporter.service
    state: absent

- name: Reload systemD
  systemd:
    daemon_reload: yes

- name: Delete the bin
  file:
    path: /usr/local/bin/node_exporter
    state: absent

- name: Delete user
  user:
    name: node_exporter
    state: absent
    group: node_exporter
    shell: "/sbin/nologin"

- name: Delete the node exporter config
  file:
    path: /etc/default/node_exporter
    state: absent
